{"uuid":"4cf5bef3-e531-4f3f-a6e4-dfb82c0e5318","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'url')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'url')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Suite.eval (webpack://cypress-poc/./cypress/e2e/loginpage.cy.js:13:26)\n    at Object.create (http://localhost:52967/__cypress/runner/cypress_runner.js:165083:19)\n    at context.describe.context.context (http://localhost:52967/__cypress/runner/cypress_runner.js:164770:27)\n    at createRunnable (http://localhost:52967/__cypress/runner/cypress_runner.js:148785:31)\n    at <unknown> (http://localhost:52967/__cypress/runner/cypress_runner.js:148846:14)\n    at eval (webpack://cypress-poc/./cypress/e2e/loginpage.cy.js:3:0)\n    at eval (http://localhost:52967/__cypress/tests?p=cypress\\e2e\\loginpage.cy.js:237:3)\n    at eval (http://localhost:52967/__cypress/tests?p=cypress\\e2e\\loginpage.cy.js:239:12)\n    at eval (<anonymous>)\n    at <unknown> (http://localhost:52967/__cypress/runner/cypress_runner.js:113392:23)"},"stage":"finished","steps":[],"attachments":[{"name":"loginpage.cy.js:2025-08-13T07:37:29.641Z","type":"image/png","source":"c5c72697-8d05-48a4-bb59-24f776a21471-attachment.png"}],"parameters":[],"labels":[{"name":"package","value":"cypress.e2e.loginpage.cy.js"}],"links":[],"start":1755070649635,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1755070649890}